/**
 * 대법원 나의사건검색 사건구분 코드 매핑
 * 출처: https://www.scourt.go.kr/portal/information/event/guide/index14.html
 * 총 325개 사건유형
 */

export interface CaseTypeInfo {
  code: string;
  name: string;
  category: string;
  description: string;
}

/**
 * 사건구분명 -> 코드 매핑 (검색용)
 */
export const CASE_TYPE_CODES: Record<string, string> = {
  '가단': '001',
  '가합': '002',
  '가소': '003',
  '나': '004',
  '다': '005',
  '라': '007',
  '카': '008',
  '마': '009',
  '바': '010',
  '자': '011',
  '차': '012',
  '타경': '013',
  '타기': '014',
  '파': '015',
  '호파': '016',
  '하': '017',
  '거': '018',
  '러': '020',
  '머': '021',
  '느': '022',
  '드': '023',
  '르': '024',
  '므': '025',
  '브': '026',
  '스': '027',
  '즈': '028',
  '너': '029',
  '츠': '030',
  '흐': '032',
  '구': '033',
  '누': '034',
  '두': '035',
  '루': '036',
  '부': '037',
  '수': '038',
  '재수': '040',
  '주': '041',
  '추': '043',
  '쿠': '044',
  '재추': '045',
  '후': '046',
  '재후': '047',
  '그': '048',
  '재가단': '050',
  '재가합': '051',
  '재가소': '052',
  '재나': '053',
  '재다': '054',
  '재구': '056',
  '재누': '057',
  '재차': '058',
  '재드': '059',
  '재르': '060',
  '재므': '061',
  '우': '062',
  '재우': '063',
  '재머': '064',
  '준재가단': '066',
  '준재가합': '067',
  '준재가소': '068',
  '카공': '069',
  '카합': '071',
  '카단': '072',
  '카담': '073',
  '카기': '074',
  '고합': '075',
  '감고': '076',
  '고단': '077',
  '고약': '078',
  '노': '079',
  '감노': '080',
  '도': '081',
  '감도': '082',
  '로': '083',
  '감로': '084',
  '모': '085',
  '감모': '086',
  '보': '087',
  '오': '088',
  '감오': '089',
  '조': '090',
  '초': '091',
  '감초': '092',
  '코': '093',
  '토': '094',
  '감토': '095',
  '푸': '098',
  '크': '099',
  '정': '100',
  '정로': '101',
  '정모': '103',
  '준재나': '105',
  '준재머': '106',
  '호': '107',
  '수흐': '109',
  '으': '110',
  '트': '111',
  '재고합': '112',
  '재고단': '113',
  '재고약': '114',
  '재노': '115',
  '재도': '116',
  '재감고': '117',
  '재감노': '118',
  '재감도': '119',
  '타': '120',
  '재타경': '122',
  '재마': '123',
  '재그': '124',
  '준재자': '125',
  '사': '126',
  '아': '127',
  '재두': '128',
  '허': '129',
  '히': '130',
  '카허': '131',
  '재허': '132',
  '무': '133',
  '재자': '134',
  '버': '135',
  '서': '136',
  '어': '137',
  '저': '138',
  '재아': '139',
  '준재구': '140',
  '준재누': '141',
  '준재아': '142',
  '준재드': '143',
  '준재르': '144',
  '준재므': '145',
  '재브': '146',
  '재스': '147',
  '준재브': '148',
  '준재스': '149',
  '드단': '150',
  '드합': '151',
  '재드단': '152',
  '재드합': '153',
  '준재드단': '154',
  '준재드합': '155',
  '준재너단': '160',
  '준재너합': '161',
  '느단': '162',
  '느합': '163',
  '재느단': '164',
  '재느합': '165',
  '준재느단': '166',
  '준재느합': '167',
  '재라': '168',
  '준재두': '169',
  '준재다': '170',
  '금': '171',
  '증': '172',
  '물': '173',
  '준재라': '174',
  '재하': '175',
  '준재하': '176',
  '즈단': '177',
  '즈합': '178',
  '과': '179',
  '회': '180',
  '선': '181',
  '유': '182',
  '재너': '183',
  '재무': '184',
  '준재타경': '185',
  '준재루': '186',
  '푸초': '187',
  '재루': '188',
  '재카합': '189',
  '재카단': '190',
  '재카담': '191',
  '재카기': '192',
  '영장': '193',
  '구단': '194',
  '구합': '195',
  '재구단': '196',
  '재구합': '197',
  '준재구단': '198',
  '준재구합': '199',
  '타채': '200',
  '카명': '201',
  '화': '202',
  '책': '203',
  '초적': '204',
  '초보': '205',
  '초기': '206',
  '파합': '207',
  '파단': '208',
  '하합': '209',
  '하단': '210',
  '즈기': '211',
  '카조': '212',
  '카구': '213',
  '하면': '214',
  '비합': '215',
  '비단': '216',
  '재카구': '217',
  '재과': '218',
  '준재카합': '219',
  '준재카단': '220',
  '준재카담': '221',
  '준재카기': '222',
  '준재과': '223',
  '재타기': '224',
  '재즈단': '225',
  '재즈합': '226',
  '고정': '230',
  '재고정': '231',
  '고약전': '234',
  '초사': '235',
  '카불': '236',
  '정가': '240',
  '정명': '241',
  '정라': '242',
  '정마': '243',
  '정고': '244',
  '정드': '245',
  '정브': '246',
  '정스': '247',
  '정기': '248',
  '재즈기': '251',
  '준재즈기': '252',
  '개회': '253',
  '개확': '254',
  '개보': '255',
  '하보': '256',
  '화보': '257',
  '회보': '258',
  '버집': '259',
  '성': '260',
  '성로': '261',
  '성모': '262',
  '성초': '263',
  '전로': '264',
  '전고': '265',
  '전노': '266',
  '전도': '267',
  '전오': '268',
  '전초': '269',
  '전모': '270',
  '재비합': '271',
  '재비단': '272',
  '재흐': '275',
  '재정가': '280',
  '재정명': '281',
  '재정라': '282',
  '재정마': '283',
  '재정고': '284',
  '재정드': '285',
  '재정브': '286',
  '재정스': '287',
  '재정기': '288',
  '개기': '290',
  '회단': '291',
  '회합': '292',
  '회확': '293',
  '회기': '294',
  '하확': '295',
  '하기': '296',
  '국승': '297',
  '국지': '298',
  '타인': '300',
  '타배': '301',
  '간회단': '302',
  '간회합': '303',
  '재으': '310',
  '재부': '311',
  '행심': '320',
  '치고': '360',
  '치노': '361',
  '치도': '362',
  '치오': '363',
  '치초': '364',
  '초치': '365',
  '치로': '366',
  '치모': '367',
  '재버': '374',
  '보고': '380',
  '보노': '381',
  '보도': '382',
  '보오': '383',
  '보초': '384',
  '보로': '385',
  '보모': '386',
  '차전': '400',
  '카기전': '401',
  '카확': '411',
  '카열': '421',
  '초재': '422',
  '호기': '423',
  '호명': '424',
  '호협': '425',
  '인': '430',
  '인라': '431',
  '인마': '432',
  '인카': '433',
  '처': '436',
  '커': '437',
  '터': '438',
  '처집': '439',
  '동버': '440',
  '동서': '441',
  '동어': '442',
  '동저': '443',
  '동버집': '444',
  '재동버': '445',
  '재동서': '446',
  '재동어': '447',
  '카임': '451',
  '카정': '452',
  '카경': '453',
  '카소': '454',
  '재카경': '455',
  '후개': '461',
  '후감': '462',
  '후기': '463',
  '동처': '501',
  '동커': '502',
  '동터': '503',
  '동처집': '504',
  '푸집': '510',
  '본': '601',
  '가': '602',
  '징': '603',
};

/**
 * 상세 정보 포함한 전체 사건유형 데이터
 */
export const CASE_TYPE_INFO: CaseTypeInfo[] = [
  { code: '001', name: '가단', category: '민사', description: '민사1심단독사건' },
  { code: '002', name: '가합', category: '민사', description: '민사1심합의사건' },
  { code: '003', name: '가소', category: '민사', description: '민사소액사건' },
  { code: '004', name: '나', category: '민사', description: '민사항소사건' },
  { code: '005', name: '다', category: '민사', description: '민사상고사건' },
  { code: '007', name: '라', category: '민사', description: '민사항고사건' },
  { code: '008', name: '카', category: '신청', description: '민사가압류,가처분등사건' },
  { code: '009', name: '마', category: '민사', description: '민사재항고사건' },
  { code: '010', name: '바', category: '민사', description: '민사준항고사건' },
  { code: '011', name: '자', category: '민사', description: '화해사건' },
  { code: '012', name: '차', category: '민사', description: '독촉사건' },
  { code: '013', name: '타경', category: '집행', description: '부동산등경매사건' },
  { code: '014', name: '타기', category: '집행', description: '기타집행사건' },
  { code: '015', name: '파', category: '비송도산', description: '비송사건' },
  { code: '016', name: '호파', category: '가족관계등록공탁', description: '가족관계등록사건' },
  { code: '017', name: '하', category: '비송도산', description: '파산사건' },
  { code: '018', name: '거', category: '비송도산', description: '도산화의사건' },
  { code: '020', name: '러', category: '민사', description: '민사공조사건' },
  { code: '021', name: '머', category: '민사', description: '민사조정사건' },
  { code: '022', name: '느', category: '가사', description: '가사비송사건' },
  { code: '023', name: '드', category: '가사', description: '가사1심사건' },
  { code: '024', name: '르', category: '가사', description: '가사항소사건' },
  { code: '025', name: '므', category: '가사', description: '가사상고사건' },
  { code: '026', name: '브', category: '가사', description: '가사항고사건' },
  { code: '027', name: '스', category: '가사', description: '가사재항고사건' },
  { code: '028', name: '즈', category: '가사', description: '가사가압류,가처분등사건' },
  { code: '029', name: '너', category: '가사', description: '가사조정사건' },
  { code: '030', name: '츠', category: '가사', description: '가사공조사건' },
  { code: '032', name: '흐', category: '특허', description: '특허재항고사건' },
  { code: '033', name: '구', category: '행정', description: '행정1심사건' },
  { code: '034', name: '누', category: '행정', description: '행정항소사건' },
  { code: '035', name: '두', category: '행정', description: '행정상고사건' },
  { code: '036', name: '루', category: '행정', description: '행정항고사건' },
  { code: '037', name: '부', category: '행정', description: '행정특별항고사건' },
  { code: '038', name: '수', category: '선거특별', description: '선거소송사건' },
  { code: '040', name: '재수', category: '선거특별', description: '선거소송사건재심' },
  { code: '041', name: '주', category: '선거특별', description: '선거신청사건' },
  { code: '043', name: '추', category: '선거특별', description: '특수소송사건' },
  { code: '044', name: '쿠', category: '선거특별', description: '특수신청사건' },
  { code: '045', name: '재추', category: '선거특별', description: '특수소송사건재심' },
  { code: '046', name: '후', category: '특허', description: '특허상고사건' },
  { code: '047', name: '재후', category: '특허', description: '특허상고사건재심' },
  { code: '048', name: '그', category: '민사', description: '민사특별항고사건' },
  { code: '050', name: '재가단', category: '민사', description: '민사1심단독사건재심' },
  { code: '051', name: '재가합', category: '민사', description: '민사1심합의사건재심' },
  { code: '052', name: '재가소', category: '민사', description: '민사소액사건재심' },
  { code: '053', name: '재나', category: '민사', description: '민사항소사건재심' },
  { code: '054', name: '재다', category: '민사', description: '민사상고사건재심' },
  { code: '056', name: '재구', category: '행정', description: '행정1심사건재심' },
  { code: '057', name: '재누', category: '행정', description: '행정항소사건재심' },
  { code: '058', name: '재차', category: '민사', description: '독촉사건재심' },
  { code: '059', name: '재드', category: '가사', description: '가사1심사건재심' },
  { code: '060', name: '재르', category: '가사', description: '가사항소사건재심' },
  { code: '061', name: '재므', category: '가사', description: '가사상고사건재심' },
  { code: '062', name: '우', category: '선거특별', description: '선거상고사건' },
  { code: '063', name: '재우', category: '선거특별', description: '선거상고사건재심' },
  { code: '064', name: '재머', category: '민사', description: '민사조정사건재심' },
  { code: '066', name: '준재가단', category: '민사', description: '민사1심단독사건준재심' },
  { code: '067', name: '준재가합', category: '민사', description: '민사1심합의사건준재심' },
  { code: '068', name: '준재가소', category: '민사', description: '민사소액사건준재심' },
  { code: '069', name: '카공', category: '신청', description: '공시최고사건' },
  { code: '071', name: '카합', category: '신청', description: '민사가압류,가처분등합의사건' },
  { code: '072', name: '카단', category: '신청', description: '민사가압류,가처분등단독사건' },
  { code: '073', name: '카담', category: '신청', description: '담보취소등사건' },
  { code: '074', name: '카기', category: '신청', description: '기타민사신청사건' },
  { code: '075', name: '고합', category: '형사', description: '형사1심합의사건' },
  { code: '076', name: '감고', category: '형사', description: '치료감호1심사건' },
  { code: '077', name: '고단', category: '형사', description: '형사1심단독사건' },
  { code: '078', name: '고약', category: '형사', description: '약식사건' },
  { code: '079', name: '노', category: '형사', description: '형사항소사건' },
  { code: '080', name: '감노', category: '형사', description: '치료감호항소사건' },
  { code: '081', name: '도', category: '형사', description: '형사상고사건' },
  { code: '082', name: '감도', category: '형사', description: '치료감호상고사건' },
  { code: '083', name: '로', category: '형사', description: '형사항고사건' },
  { code: '084', name: '감로', category: '형사', description: '치료감호항고사건' },
  { code: '085', name: '모', category: '형사', description: '형사재항고사건' },
  { code: '086', name: '감모', category: '형사', description: '치료감호재항고사건' },
  { code: '087', name: '보', category: '형사', description: '형사준항고사건' },
  { code: '088', name: '오', category: '형사', description: '비상상고사건' },
  { code: '089', name: '감오', category: '형사', description: '치료감호비상상고사건' },
  { code: '090', name: '조', category: '형사', description: '즉결심판사건' },
  { code: '091', name: '초', category: '형사', description: '형사신청사건' },
  { code: '092', name: '감초', category: '형사', description: '치료감호신청사건' },
  { code: '093', name: '코', category: '형사', description: '형사보상청구사건' },
  { code: '094', name: '토', category: '형사', description: '형사공조사건' },
  { code: '095', name: '감토', category: '형사', description: '치료감호공조사건' },
  { code: '098', name: '푸', category: '보호', description: '소년보호사건' },
  { code: '099', name: '크', category: '보호', description: '소년보호항고사건' },
  { code: '100', name: '정', category: '감치', description: '감치,과태료' },
  { code: '101', name: '정로', category: '감치', description: '법정질서위반감치등항고사건' },
  { code: '103', name: '정모', category: '감치', description: '법정질서위반감치등재항고사건' },
  { code: '105', name: '준재나', category: '민사', description: '민사항소사건준재심' },
  { code: '106', name: '준재머', category: '민사', description: '민사조정사건준재심' },
  { code: '107', name: '호', category: '가족관계등록공탁', description: '협의이혼사건' },
  { code: '109', name: '수흐', category: '선거특별', description: '선거항고(재항고,준항고,특별항고)사건' },
  { code: '110', name: '으', category: '가사', description: '가사특별항고사건' },
  { code: '111', name: '트', category: '보호', description: '소년보호재항고사건' },
  { code: '112', name: '재고합', category: '형사', description: '형사1심합의사건재심' },
  { code: '113', name: '재고단', category: '형사', description: '형사1심단독사건재심' },
  { code: '114', name: '재고약', category: '형사', description: '약식사건재심' },
  { code: '115', name: '재노', category: '형사', description: '형사항소사건재심' },
  { code: '116', name: '재도', category: '형사', description: '형사상고사건재심' },
  { code: '117', name: '재감고', category: '형사', description: '치료감호1심사건재심' },
  { code: '118', name: '재감노', category: '형사', description: '치료감호항소사건재심' },
  { code: '119', name: '재감도', category: '형사', description: '치료감호상고사건재심' },
  { code: '120', name: '타', category: '집행', description: '집행사건' },
  { code: '122', name: '재타경', category: '집행', description: '부동산등경매사건재심' },
  { code: '123', name: '재마', category: '민사', description: '민사재항고사건재심' },
  { code: '124', name: '재그', category: '민사', description: '민사특별항고사건재심' },
  { code: '125', name: '준재자', category: '민사', description: '화해사건준재심' },
  { code: '126', name: '사', category: '행정', description: '행정준항고사건' },
  { code: '127', name: '아', category: '행정', description: '행정신청사건' },
  { code: '128', name: '재두', category: '행정', description: '행정상고사건재심' },
  { code: '129', name: '허', category: '특허', description: '특허1심사건' },
  { code: '130', name: '히', category: '특허', description: '특허특별(준)항고사건' },
  { code: '131', name: '카허', category: '특허', description: '특허신청사건' },
  { code: '132', name: '재허', category: '특허', description: '특허1심사건재심' },
  { code: '133', name: '무', category: '행정', description: '행정재항고사건' },
  { code: '134', name: '재자', category: '민사', description: '화해사건재심' },
  { code: '135', name: '버', category: '보호', description: '가정보호사건' },
  { code: '136', name: '서', category: '보호', description: '가정보호항고사건' },
  { code: '137', name: '어', category: '보호', description: '가정보호재항고사건' },
  { code: '138', name: '저', category: '보호', description: '가정보호신청사건' },
  { code: '139', name: '재아', category: '행정', description: '행정신청사건재심' },
  { code: '140', name: '준재구', category: '행정', description: '행정1심사건준재심' },
  { code: '141', name: '준재누', category: '행정', description: '행정항소사건준재심' },
  { code: '142', name: '준재아', category: '행정', description: '행정신청사건준재심' },
  { code: '143', name: '준재드', category: '가사', description: '가사1심사건준재심' },
  { code: '144', name: '준재르', category: '가사', description: '가사항소사건준재심' },
  { code: '145', name: '준재므', category: '가사', description: '가사상고사건준재심' },
  { code: '146', name: '재브', category: '가사', description: '가사항고사건재심' },
  { code: '147', name: '재스', category: '가사', description: '가사재항고사건재심' },
  { code: '148', name: '준재브', category: '가사', description: '가사항고사건준재심' },
  { code: '149', name: '준재스', category: '가사', description: '가사재항고사건준재심' },
  { code: '150', name: '드단', category: '가사', description: '가사1심단독사건' },
  { code: '151', name: '드합', category: '가사', description: '가사1심합의사건' },
  { code: '152', name: '재드단', category: '가사', description: '가사1심단독사건재심' },
  { code: '153', name: '재드합', category: '가사', description: '가사1심합의사건재심' },
  { code: '154', name: '준재드단', category: '가사', description: '가사1심단독사건준재심' },
  { code: '155', name: '준재드합', category: '가사', description: '가사1심합의사건준재심' },
  { code: '160', name: '준재너단', category: '가사', description: '조정 단독 사건 준재심' },
  { code: '161', name: '준재너합', category: '가사', description: '조정 합의 사건 준재심' },
  { code: '162', name: '느단', category: '가사', description: '가사비송단독사건' },
  { code: '163', name: '느합', category: '가사', description: '가사비송합의사건' },
  { code: '164', name: '재느단', category: '가사', description: '가사비송단독사건재심' },
  { code: '165', name: '재느합', category: '가사', description: '가사비송합의사건재심' },
  { code: '166', name: '준재느단', category: '가사', description: '가사비송단독사건준재심' },
  { code: '167', name: '준재느합', category: '가사', description: '가사비송합의사건준재심' },
  { code: '168', name: '재라', category: '민사', description: '민사항고사건재심' },
  { code: '169', name: '준재두', category: '행정', description: '행정상고사건준재심' },
  { code: '170', name: '준재다', category: '민사', description: '민사상고사건준재심' },
  { code: '171', name: '금', category: '가족관계등록공탁', description: '공탁사건(금전)' },
  { code: '172', name: '증', category: '가족관계등록공탁', description: '공탁사건(증권)' },
  { code: '173', name: '물', category: '가족관계등록공탁', description: '공탁사건(물품)' },
  { code: '174', name: '준재라', category: '민사', description: '민사항고사건준재심' },
  { code: '175', name: '재하', category: '비송도산', description: '파산사건재심' },
  { code: '176', name: '준재하', category: '비송도산', description: '파산사건준재심' },
  { code: '177', name: '즈단', category: '가사', description: '가사가압류,가처분등단독사건' },
  { code: '178', name: '즈합', category: '가사', description: '가사가압류,가처분등합의사건' },
  { code: '179', name: '과', category: '비송도산', description: '과태료사건' },
  { code: '180', name: '회', category: '비송도산', description: '회사정리사건' },
  { code: '181', name: '선', category: '비송도산', description: '선박소유자등의책임제한사건' },
  { code: '182', name: '유', category: '비송도산', description: '유류오염손해배상책임제한사건' },
  { code: '183', name: '재너', category: '가사', description: '가사조정사건재심' },
  { code: '184', name: '재무', category: '행정', description: '행정재항고사건재심' },
  { code: '185', name: '준재타경', category: '집행', description: '부동산등경매사건준재심' },
  { code: '186', name: '준재루', category: '행정', description: '행정신청항고사건준재심' },
  { code: '187', name: '푸초', category: '보호', description: '소년보호신청사건' },
  { code: '188', name: '재루', category: '행정', description: '행정신청항고사건재심' },
  { code: '189', name: '재카합', category: '신청', description: '민사가압류,가처분등합의사건재심' },
  { code: '190', name: '재카단', category: '신청', description: '민사가압류,가처분등단독사건재심' },
  { code: '191', name: '재카담', category: '신청', description: '담보취소등사건재심' },
  { code: '192', name: '재카기', category: '신청', description: '기타민사신청사건재심' },
  { code: '193', name: '영장', category: '기타', description: '영장' },
  { code: '194', name: '구단', category: '행정', description: '행정1심재정단독사건' },
  { code: '195', name: '구합', category: '행정', description: '행정1심사건' },
  { code: '196', name: '재구단', category: '행정', description: '행정1심재정단독사건재심' },
  { code: '197', name: '재구합', category: '행정', description: '행정1심사건재심' },
  { code: '198', name: '준재구단', category: '행정', description: '행정1심재정단독사건준재심' },
  { code: '199', name: '준재구합', category: '행정', description: '행정1심사건준재심' },
  { code: '200', name: '타채', category: '집행', description: '채권등집행사건' },
  { code: '201', name: '카명', category: '신청', description: '재산명시등사건' },
  { code: '202', name: '화', category: '비송도산', description: '도산화의사건' },
  { code: '203', name: '책', category: '비송도산', description: '선박,유류등책임제한사건' },
  { code: '204', name: '초적', category: '형사', description: '체포,구속적부심사건' },
  { code: '205', name: '초보', category: '형사', description: '보석사건' },
  { code: '206', name: '초기', category: '형사', description: '기타형사신청사건' },
  { code: '207', name: '파합', category: '비송도산', description: '비송합의사건' },
  { code: '208', name: '파단', category: '비송도산', description: '비송단독사건' },
  { code: '209', name: '하합', category: '비송도산', description: '파산합의사건' },
  { code: '210', name: '하단', category: '비송도산', description: '파산단독사건' },
  { code: '211', name: '즈기', category: '가사', description: '기타가사신청사건' },
  { code: '212', name: '카조', category: '신청', description: '재산조회사건' },
  { code: '213', name: '카구', category: '신청', description: '소송구조등사건' },
  { code: '214', name: '하면', category: '비송도산', description: '면책사건' },
  { code: '215', name: '비합', category: '비송도산', description: '비송합의사건' },
  { code: '216', name: '비단', category: '비송도산', description: '비송단독사건' },
  { code: '217', name: '재카구', category: '신청', description: '소송구조등사건재심' },
  { code: '218', name: '재과', category: '비송도산', description: '과태료사건재심' },
  { code: '219', name: '준재카합', category: '신청', description: '민사가압류,가처분등합의사건준재심' },
  { code: '220', name: '준재카단', category: '신청', description: '민사가압류,가처분등단독사건준재심' },
  { code: '221', name: '준재카담', category: '신청', description: '담보취소등사건준재심' },
  { code: '222', name: '준재카기', category: '신청', description: '기타민사신청사건준재심' },
  { code: '223', name: '준재과', category: '비송도산', description: '과태료사건준재심' },
  { code: '224', name: '재타기', category: '집행', description: '기타집행사건재심' },
  { code: '225', name: '재즈단', category: '가사', description: '가사가압류,가처분등단독사건재심' },
  { code: '226', name: '재즈합', category: '가사', description: '가사가압류,가처분등합의사건재심' },
  { code: '230', name: '고정', category: '형사', description: '약식정재청구1심단독사건' },
  { code: '231', name: '재고정', category: '형사', description: '약식정재청구1심단독사건(재심)' },
  { code: '234', name: '고약전', category: '전자약식', description: '전자약식사건' },
  { code: '235', name: '초사', category: '형사', description: '사회봉사허가청구사건/사회봉사허가취소청구사건' },
  { code: '236', name: '카불', category: '신청', description: '채무불이행자명부등재사건' },
  { code: '240', name: '정가', category: '감치', description: '증인감치사건' },
  { code: '241', name: '정명', category: '감치', description: '채무자감치사건' },
  { code: '242', name: '정라', category: '감치', description: '증인·채무자감치항고사건' },
  { code: '243', name: '정마', category: '감치', description: '증인·채무자감치재항고사건' },
  { code: '244', name: '정고', category: '감치', description: '법정질서위반감치등사건' },
  { code: '245', name: '정드', category: '감치', description: '의무불이행자감치등사건' },
  { code: '246', name: '정브', category: '감치', description: '의무불이행자감치등항고사건' },
  { code: '247', name: '정스', category: '감치', description: '의무불이행자감치등재항고사건' },
  { code: '248', name: '정기', category: '감치', description: '기타감치신청사건' },
  { code: '251', name: '재즈기', category: '가사', description: '기타가사신청사건재심' },
  { code: '252', name: '준재즈기', category: '가사', description: '기타가사신청사건준재심' },
  { code: '253', name: '개회', category: '비송도산', description: '개인회생사건' },
  { code: '254', name: '개확', category: '비송도산', description: '개인회생채권조사확정사건' },
  { code: '255', name: '개보', category: '비송도산', description: '개인회생보전처분사건' },
  { code: '256', name: '하보', category: '비송도산', description: '파산보전처분사건' },
  { code: '257', name: '화보', category: '비송도산', description: '도산화의보전처분사건' },
  { code: '258', name: '회보', category: '비송도산', description: '회사정리보전처분사건' },
  { code: '259', name: '버집', category: '보호', description: '가정보호집행감독사건' },
  { code: '260', name: '성', category: '보호', description: '성매매관련보호사건' },
  { code: '261', name: '성로', category: '보호', description: '성매매관련보호항고사건' },
  { code: '262', name: '성모', category: '보호', description: '성매매관련보호재항고사건' },
  { code: '263', name: '성초', category: '보호', description: '성매매관련보호신청사건' },
  { code: '264', name: '전로', category: '형사', description: '부착명령항고사건' },
  { code: '265', name: '전고', category: '형사', description: '부착명령청구1심사건' },
  { code: '266', name: '전노', category: '형사', description: '부착명령청구사건 항소' },
  { code: '267', name: '전도', category: '형사', description: '부착명령청구사건 상고' },
  { code: '268', name: '전오', category: '형사', description: '부착명령청구사건 비상상고' },
  { code: '269', name: '전초', category: '형사', description: '부착명령신청사건' },
  { code: '270', name: '전모', category: '형사', description: '부착명령재항고사건' },
  { code: '271', name: '재비합', category: '비송도산', description: '비송합의사건재심' },
  { code: '272', name: '재비단', category: '비송도산', description: '비송단독사건재심' },
  { code: '275', name: '재흐', category: '특허', description: '특허재항고사건재심' },
  { code: '280', name: '재정가', category: '감치', description: '증인감치사건재심' },
  { code: '281', name: '재정명', category: '감치', description: '채무자감치사건재심' },
  { code: '282', name: '재정라', category: '감치', description: '증인·채무자감치항고사건재심' },
  { code: '283', name: '재정마', category: '감치', description: '증인·채무자감치재항고사건재심' },
  { code: '284', name: '재정고', category: '감치', description: '법정질서위반감치등사건재심' },
  { code: '285', name: '재정드', category: '감치', description: '의무불이행자감치등사건재심' },
  { code: '286', name: '재정브', category: '감치', description: '의무불이행자감치등항고사건재심' },
  { code: '287', name: '재정스', category: '감치', description: '의무불이행자감치등재항고사건재심' },
  { code: '288', name: '재정기', category: '감치', description: '기타감치신청사건재심' },
  { code: '290', name: '개기', category: '비송도산', description: '기타개인회생관련신청사건' },
  { code: '291', name: '회단', category: '비송도산', description: '회생단독사건' },
  { code: '292', name: '회합', category: '비송도산', description: '회생합의사건' },
  { code: '293', name: '회확', category: '비송도산', description: '회생채권ㆍ회생담보권조사확정사건' },
  { code: '294', name: '회기', category: '비송도산', description: '기타회생관련신청사건' },
  { code: '295', name: '하확', category: '비송도산', description: '파산채권조사확정사건' },
  { code: '296', name: '하기', category: '비송도산', description: '기타파산ㆍ면책관련신청사건' },
  { code: '297', name: '국승', category: '비송도산', description: '국제도산승인사건' },
  { code: '298', name: '국지', category: '비송도산', description: '국제도산지원사건' },
  { code: '300', name: '타인', category: '집행', description: '부동산인도명령사건' },
  { code: '301', name: '타배', category: '집행', description: '채권배당사건' },
  { code: '302', name: '간회단', category: '비송도산', description: '간이회생단독사건' },
  { code: '303', name: '간회합', category: '비송도산', description: '간이회생합의사건' },
  { code: '310', name: '재으', category: '가사', description: '가사특별항고사건' },
  { code: '311', name: '재부', category: '행정', description: '행정특별항고사건' },
  { code: '320', name: '행심', category: '기타', description: '행정심판사건' },
  { code: '360', name: '치고', category: '형사', description: '치료명령1심사건' },
  { code: '361', name: '치노', category: '형사', description: '치료명령항소사건' },
  { code: '362', name: '치도', category: '형사', description: '치료명령상고사건' },
  { code: '363', name: '치오', category: '형사', description: '치료명령비상상고사건' },
  { code: '364', name: '치초', category: '형사', description: '치료명령신청(치료기간연장, 준수사항추가·변경·삭제청구)사건' },
  { code: '365', name: '초치', category: '형사', description: '성폭력수형자치료명령1심사건' },
  { code: '366', name: '치로', category: '형사', description: '치료명령항고사건' },
  { code: '367', name: '치모', category: '형사', description: '치료명령재항고사건' },
  { code: '374', name: '재버', category: '보호', description: '가정보호사건재심' },
  { code: '380', name: '보고', category: '형사', description: '보호관찰명령1심사건' },
  { code: '381', name: '보노', category: '형사', description: '보호관찰명령항소사건' },
  { code: '382', name: '보도', category: '형사', description: '보호관찰명령상고사건' },
  { code: '383', name: '보오', category: '형사', description: '보호관찰명령비상상고사건' },
  { code: '384', name: '보초', category: '형사', description: '보호관찰명령신청사건' },
  { code: '385', name: '보로', category: '형사', description: '보호관찰명령항고사건' },
  { code: '386', name: '보모', category: '형사', description: '보호관찰명령재항고사건' },
  { code: '400', name: '차전', category: '기타', description: '전자독촉사건' },
  { code: '401', name: '카기전', category: '신청', description: '전자독촉사건 경정신청사건' },
  { code: '411', name: '카확', category: '신청', description: '소송비용 확정을 위한 신청사건' },
  { code: '421', name: '카열', category: '신청', description: '확정된 소송기록에 대한 열람신청사건' },
  { code: '422', name: '초재', category: '형사', description: '재정신청사건/재정신청 비용지급신청사건' },
  { code: '423', name: '호기', category: '가족관계등록공탁', description: '가족관계등록(제적)비송사건' },
  { code: '424', name: '호명', category: '가족관계등록공탁', description: '개명사건' },
  { code: '425', name: '호협', category: '가족관계등록공탁', description: '협의이혼사건' },
  { code: '430', name: '인', category: '보호', description: '인신보호사건' },
  { code: '431', name: '인라', category: '보호', description: '인신보호항고사건' },
  { code: '432', name: '인마', category: '보호', description: '인신보호재항고사건' },
  { code: '433', name: '인카', category: '보호', description: '인신보호신청사건' },
  { code: '436', name: '처', category: '보호', description: '피해자보호명령사건' },
  { code: '437', name: '커', category: '보호', description: '자보호명령항고사건' },
  { code: '438', name: '터', category: '보호', description: '자보호명령재항고사건' },
  { code: '439', name: '처집', category: '보호', description: '피해자보호명령집행감독사건' },
  { code: '440', name: '동버', category: '보호', description: '아동보호사건' },
  { code: '441', name: '동서', category: '보호', description: '아동보호항고사건' },
  { code: '442', name: '동어', category: '보호', description: '아동보호재항고사건' },
  { code: '443', name: '동저', category: '보호', description: '아동보호신청사건' },
  { code: '444', name: '동버집', category: '보호', description: '아동보호집행사건' },
  { code: '445', name: '재동버', category: '보호', description: '아동보호사건재심' },
  { code: '446', name: '재동서', category: '보호', description: '아동보호항고사건재심' },
  { code: '447', name: '재동어', category: '보호', description: '아동보호재항고사건재심' },
  { code: '451', name: '카임', category: '신청', description: '임차권등기명령등사건' },
  { code: '452', name: '카정', category: '신청', description: '강제집행정지사건' },
  { code: '453', name: '카경', category: '신청', description: '판결(결정)경정사건' },
  { code: '454', name: '카소', category: '신청', description: '제소명령사건' },
  { code: '455', name: '재카경', category: '신청', description: '판결(결정)경정사건재심' },
  { code: '461', name: '후개', category: '가사', description: '후견개시사건' },
  { code: '462', name: '후감', category: '가사', description: '후견감독사건' },
  { code: '463', name: '후기', category: '가사', description: '기타후견사건' },
  { code: '501', name: '동처', category: '보호', description: '피해아동보호명령사건' },
  { code: '502', name: '동커', category: '보호', description: '피해아동보호명령항고사건' },
  { code: '503', name: '동터', category: '보호', description: '피해아동보호명령재항고사건' },
  { code: '504', name: '동처집', category: '보호', description: '피해아동보호명령집행감독사건' },
  { code: '510', name: '푸집', category: '보호', description: '소년보호집행감독사건' },
  { code: '601', name: '본', category: '집행', description: '동산경매, 부동산인도명도철거 등' },
  { code: '602', name: '가', category: '집행', description: '동산가압류, 동산가처분, 부동산가처분' },
  { code: '603', name: '징', category: '집행', description: '징수' },
];

/**
 * 사건구분명으로 코드 조회
 */
export function getCaseTypeCodeByName(caseTypeName: string): string | undefined {
  return CASE_TYPE_CODES[caseTypeName];
}

/**
 * 코드로 사건유형 정보 조회
 */
export function getCaseTypeInfoByCode(code: string): CaseTypeInfo | undefined {
  return CASE_TYPE_INFO.find(info => info.code === code);
}

/**
 * 사건구분명으로 카테고리 조회
 */
export function getCaseCategoryByTypeName(caseTypeName: string): string | undefined {
  const code = CASE_TYPE_CODES[caseTypeName];
  if (!code) return undefined;
  const info = CASE_TYPE_INFO.find(i => i.code === code);
  return info?.category;
}
